services:
  catalogue:
    build: 
      dockerfile = catalogue.Dockerfile
    image : battulaswathi/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb 
  mongodb:
    build: 
      dockerfile = mongodb.Dockerfile
    image : battulaswathi/mongodb:1.0.0
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false



























































