services:
  catalogue:
    build: ./catalogue
    image : battulaswathi/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb 
  user:
    build: ./user
    image : battulaswathi/user:1.0.0
    container_name: user
    depends_on: 
    - redis
  cart:
    build: ./cart
    image : battulaswathi/cart:1.0.0
    container_name: cart
    depends_on: 
    - redis
  frontend:
    build: ./frontend
    image : battulaswathi/frontend:1.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on: 
    - catalogue
    - user
    - cart
  mongodb:
    build: ./mongodb
    image : battulaswathi/mongodb:1.0.0
    container_name: mongodb
  redis:
    image: redis:7.0
    container_name: redis
  mysql:
    build: ./mysql
    image : battulaswathi/mysql:1.0.0
    container_name: mysql

networks:
  default:
    driver: bridge
    name: roboshop
    external: true